dist: xenial   # required for Python >= 3.7
language: python
python:
  - "3.7"

# Install dependencies
install:
  - pip install -r requirements.txt

# command to run tests
script:
  - python -m pytest -v --cov=./

after_success:
  - codecov

addons:
  sonarcloud:
    organization: "rafaelschlatter_pipedesign-ml" # the key of the org you chose at step #3
    token:
      secure: SONAR_TOKEN # encrypted value of your token
script:
  # other script steps might be done before running the actual analysis
  - sonar-scanner
